backend:
  name: github
  repo: uptdairminumkotasorong-commits/layanan-air-minum-sorong
  branch: main
media_folder: "assets/images"
public_folder: "/assets/images"
collections:
  - name: "berita"
    label: "Berita"
    files:
      - name: "data_berita"
        label: "Daftar Berita"
        file: "data/berita.json"
        fields:
          - name: "items"
            label: "Daftar Berita"
            widget: "list"
            fields:
              - {label: "Judul", name: "title", widget: "string"}
              - {label: "Tanggal", name: "date", widget: "datetime"}
              - {label: "Isi Berita", name: "body", widget: "text"}
