backend:
  name: github
  repo: uptdairminumkotasorong-commits/layanan-air-minum-sorong
  branch: main
media_folder: "assets/images"
public_folder: "/assets/images"
collections:
  - name: "berita"
    label: "Berita"
    folder: "content/berita"
    create: true
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Isi", name: "body", widget: "markdown"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
